---
namespace: ngine_io
name: hashi
version: 1.0.0
readme: README.md
authors:
  - René Moser <mail@renemoser.net>
description: Hashicorp Stack Collection
license:
  - GPL-3.0-or-later
tags:
  - hashicorp
  - nomad
  - consul
dependencies: {}
repository: https://github.com/ngine-io/ansible-collection-hashi
documentation: https://ngine-io.github.io/ansible-collection-hashi/
homepage: https://ngine-io.github.io/ansible-collection-hashi/
issues: https://github.com/ngine-io/ansible-collection-hashi/issues
build_ignore: []
