---
- name: Configure the Hashicorp apt repository
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure the Hashicorp yum repository
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
